# Simple workflow for deploying static content to GitHub Pages
name: Deploy Sphinx Document to Branch

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Check poetry
        run: |
          poetry --version
          poetry config --list
      - name: Install dependencies
        run: poetry install
      - name: Install Sphinx RTD Theme
        run: poetry add sphinx_rtd_theme
      - name: Build Sphinx
        run: |
          poetry run make html
      - name: Create .nojekyll file
        run: echo "" > ./build/html/.nojekyll
      - name: Push build to a separate branch
        run: |
          git config --local user.email "akira_kumita@demia.co.jp"  
          git config --local user.name "kumitaakira453"          
          git checkout -b gh-pages || git checkout gh-pages  # gh-pagesブランチに切り替え、新しい場合は作成
          git rm -rf .                                      # 既存のファイルを削除
          cp -r ./build/html/. ./                          # ビルドしたファイルをコピー
          git add .                                         # 新しいファイルを追加
          git commit -m "Deploy Sphinx documentation"      # コミット
          git push -f origin gh-pages                       # gh-pagesブランチにプッシュ
